M48
; DRILL file {KiCad 7.0.1-0} date 2024 February 02, Friday 12:18:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-02T12:18:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X142.89Y-77.585
X142.89Y-82.435
T2
X145.92Y-77.285
X145.92Y-82.735
T0
M30
